# ==============================================================================
# MODULE: DATABASE SEEDER SCRIPT
# Purpose: Resets and populates the laboratory database with default users,
#          real IT department equipment inventory, active borrowings, and maintenance logs.
# ==============================================================================
import sqlite3
from database import init_db


# ==============================================================================
# TOPIC: SEED DATABASE FUNCTION
# Purpose: Clears existing records and repopulates database with baseline data.
# ==============================================================================
def seed():
    # Initialize SQLite database schema
    init_db()
    conn = sqlite3.connect("inventory.db")
    cursor = conn.cursor()

    # --------------------------------------------------------------------------
    # TOPIC: CLEAR PREVIOUS DATA
    # Purpose: Wipes old rows to ensure a fresh, consistent seed state.
    # --------------------------------------------------------------------------
    cursor.execute("DELETE FROM users")
    cursor.execute("DELETE FROM equipment")
    cursor.execute("DELETE FROM transactions")
    cursor.execute("DELETE FROM maintenance")

    # --------------------------------------------------------------------------
    # TOPIC: SEED USER ACCOUNTS (M1 AUTHENTICATION)
    # Purpose: Creates sample Admin, Faculty, and Student accounts with role profiles.
    # --------------------------------------------------------------------------
    users = [
        ("admin", "admin123", "Admin", "System Administrator", "ADMIN-01", "Information Technology"),
        ("faculty", "fac123", "Faculty", "Prof. S. Sharma", "FAC-01", "Information Technology"),
        ("student", "student123", "Student", "Aditya Yadav", "125A3125", "Information Technology"),
    ]
    cursor.executemany("INSERT INTO users (username, password, role, full_name, roll_no, department) VALUES (?, ?, ?, ?, ?, ?)", users)

    # --------------------------------------------------------------------------
    # TOPIC: SEED LABORATORY EQUIPMENT CATALOG (M2 INVENTORY)
    # Purpose: Populates 78 real IT Department components, boards, and sensors.
    # --------------------------------------------------------------------------
    equipment = [
        (
            "EQ-200",
            "10 K Pot",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-201",
            "12C Module",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-202",
            "7 Segment Display",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-203",
            "ADXL345 Accelerometer",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            9,
            9,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-204",
            "Arduino Uno At Mega 328",
            "Microcontrollers",
            "Arduino",
            "IoT Lab",
            30,
            30,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-205",
            "Battery Connector",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-206",
            "BMP180",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-207",
            "BO motor Dual Craft",
            "Motors",
            "Generic",
            "IoT Lab",
            4,
            4,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-208",
            "Breadboard",
            "Prototyping",
            "Generic",
            "IoT Lab",
            31,
            31,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-209",
            "Buzzer 5 V",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-210",
            "Piezo Buzzer",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-211",
            "Color sensor TC230TCS3200",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-212",
            "DC Motor",
            "Motors",
            "Generic",
            "IoT Lab",
            14,
            14,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-213",
            "DC Motor Fan",
            "Motors",
            "Generic",
            "IoT Lab",
            10,
            10,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-214",
            "DHT 11 Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-215",
            "ECG Monitoring AdraXX ADD 8232",
            "Sensors & Components",
            "AdraXX",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-216",
            "ESP 32",
            "Microcontrollers",
            "Espressif",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-217",
            "ESP 32 Cam Module",
            "Microcontrollers",
            "Espressif",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-218",
            "Flex Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            4,
            4,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-219",
            "Gear Motor",
            "Motors",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-220",
            "GPS Module",
            "Modules",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-221",
            "GPS Module Neo 6M",
            "Modules",
            "u-blox",
            "IoT Lab",
            10,
            10,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-222",
            "GSM Module Sim 800L",
            "Modules",
            "Simcom",
            "IoT Lab",
            13,
            13,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-223",
            "GSM Module Sim 900a",
            "Modules",
            "Simcom",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-224",
            "GSM Module Sim 28NL",
            "Modules",
            "Simcom",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-226",
            "HC Bluetooth",
            "Modules",
            "Generic",
            "IoT Lab",
            21,
            21,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-227",
            "Heart Beat Pulse Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-228",
            "I2C Module",
            "Modules",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-229",
            "IR Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-230",
            "Laser Module",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-231",
            "LCD 16X2",
            "Displays",
            "Generic",
            "IoT Lab",
            45,
            45,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-232",
            "LDR Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            30,
            30,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-233",
            "LED 5 MM",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            120,
            120,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-234",
            "Line Follower Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-235",
            "LM 35 Temperature Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-236",
            "LM7805 Voltage Regulator",
            "Power Components",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-237",
            "Low Frequency RFID Detector RC522",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-238",
            "Micro HDMI to HDMI Cable",
            "Cables",
            "Generic",
            "IoT Lab",
            10,
            10,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-239",
            "Mini Servo Motor",
            "Motors",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-240",
            "MG996R Servo Motor",
            "Motors",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-241",
            "MG 90S Servo Motor Metal Gear Micro",
            "Motors",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-242",
            "Mini Water Pump 3.7 V",
            "Motors",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-243",
            "Mini 12 V DC submersible Water Pump",
            "Motors",
            "Generic",
            "IoT Lab",
            4,
            4,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-244",
            "Motor Driver L293D",
            "Modules",
            "Generic",
            "IoT Lab",
            10,
            10,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-245",
            "Motor Driver Shield L293D",
            "Modules",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-246",
            "Motor Driver L298",
            "Modules",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-247",
            "Motor Driver L298N",
            "Modules",
            "Generic",
            "IoT Lab",
            4,
            4,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-248",
            "MQ135",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-249",
            "MQ3 Alcohol Gas Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-250",
            "MQ4 Methane Gas",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-251",
            "MQ7 Gas Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-252",
            "MQ9 Methane & CO Gas",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            10,
            10,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-253",
            "Node MCU Board with Cable",
            "Microcontrollers",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-254",
            "PIR Sensor HC 501",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-255",
            "Push Button",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-256",
            "Raspberry Pi 3 Model B",
            "Microcontrollers",
            "Raspberry Pi",
            "IoT Lab",
            11,
            11,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-257",
            "Raspberry Pi Dev Kit 4",
            "Microcontrollers",
            "Raspberry Pi",
            "IoT Lab",
            10,
            10,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-258",
            "Raspberry Pi Camera",
            "Sensors & Components",
            "Raspberry Pi",
            "IoT Lab",
            10,
            10,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-259",
            "Relay Module 5V Single",
            "Modules",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-260",
            "5V 4 Channel Relay Module",
            "Modules",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-261",
            "Servo Motor Tester",
            "Modules",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-262",
            "Resistance 220 ohm",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            60,
            60,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-263",
            "RFID CARD EM18",
            "Modules",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-264",
            "Soil Moisture Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-265",
            "Soldering Gun",
            "Tools",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-266",
            "Type C Cable",
            "Cables",
            "Generic",
            "IoT Lab",
            10,
            10,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-267",
            "Ultra Sonic Sensor HCSR 04",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-268",
            "Vibration sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-269",
            "Water Rain Drop Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            7,
            7,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-270",
            "White Wheels",
            "Hardware",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-271",
            "Wifi Module",
            "Modules",
            "Generic",
            "IoT Lab",
            20,
            20,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-272",
            "MAX 30102 Pulse Oximeter Sensor",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-273",
            "L298N Dual H Bridge",
            "Modules",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-274",
            "3X1.5V AA Battery Holder",
            "Power Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-275",
            "Air Exhaust Fan Mini 5V DC",
            "Hardware",
            "Generic",
            "IoT Lab",
            2,
            2,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-276",
            "IC Socket 16 Pin",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            5,
            5,
            "Active",
            "2026-01-01",
        ),
        (
            "EQ-277",
            "3 Pin Slide Switch",
            "Sensors & Components",
            "Generic",
            "IoT Lab",
            1,
            1,
            "Active",
            "2026-01-01",
        ),
    ]
    cursor.executemany(
        "INSERT INTO equipment VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", equipment
    )

    # --------------------------------------------------------------------------
    # TOPIC: SEED SAMPLE ISSUED TRANSACTIONS (M3 TRANSACTIONS)
    # Purpose: Records active equipment borrowings assigned to real student roll numbers.
    # --------------------------------------------------------------------------
    transactions = [
        ("Aayush Sawant", "125A3091", "EQ-204", "2026-09-15", None, None, "Issued"),
        ("Arya Warang", "125A3124", "EQ-256", "2026-09-18", None, None, "Issued"),
        ("Aditya Yadav", "125A3125", "EQ-208", "2026-09-20", None, None, "Issued"),
    ]
    cursor.executemany(
        """
        INSERT INTO transactions (student_name, roll_no, equipment_id, issue_date, return_date, condition_on_return, status)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """,
        transactions,
    )

    # --------------------------------------------------------------------------
    # TOPIC: SYNC AVAILABLE STOCK FOR ISSUED ITEMS
    # Purpose: Decrements available_qty for the items currently issued above.
    # --------------------------------------------------------------------------
    cursor.execute(
        "UPDATE equipment SET available_qty = available_qty - 1 WHERE equipment_id IN ('EQ-204', 'EQ-256', 'EQ-208')"
    )

    # --------------------------------------------------------------------------
    # TOPIC: SEED MAINTENANCE & REPAIR LOGS (M4 MAINTENANCE)
    # Purpose: Records equipment undergoing technician diagnostics or repairs.
    # --------------------------------------------------------------------------
    repairs = [
        ("EQ-212", "Prof. Sharma", "2026-09-10", "Under Repair"),
        ("EQ-231", "Apex Instruments", "2026-09-05", "Repaired"),
    ]
    cursor.executemany(
        """
        INSERT INTO maintenance (equipment_id, technician_name, repair_date, status)
        VALUES (?, ?, ?, ?)
    """,
        repairs,
    )

    # --------------------------------------------------------------------------
    # TOPIC: SYNC STOCK FOR ITEMS UNDER REPAIR
    # Purpose: Adjusts quantities and marks equipment status as 'Under Repair'.
    # --------------------------------------------------------------------------
    cursor.execute(
        "UPDATE equipment SET total_qty = total_qty - 1, available_qty = available_qty - 1, status = 'Under Repair' WHERE equipment_id = 'EQ-212'"
    )

    # Commit changes and close connection
    conn.commit()
    conn.close()
    print("Database seeded with updated schema and real records.")


# ==============================================================================
# TOPIC: SCRIPT ENTRYPOINT
# Purpose: Executes database seeding when run directly as a script.
# ==============================================================================
if __name__ == "__main__":
    seed()

